zrepl/zrepl

cmd/config.go
In ezjail I deliberately avoided the concept of "months", since they're very volatile. But your concept of them being 32 weeks seems a little too generous ;)
=> Shrink the 'monthly' interval from 32 weeks to 32 days

zfs/zfs.go
Space is a allowed character in zfs names accoring to
https://github.com/zfsonlinux/zfs/issues/439.
closes: #73.
=> zfs: allow spaces in zfs names.

client/migrate.go, client/migrate_test.go, client/testcmd.go, docs/changelog.rst, docs/configuration/jobs.rst, docs/usage.rst, endpoint/endpoint.go, main.go, zfs/mapping.go, zfs/placeholder.go
As became clear in https://github.com/zrepl/zrepl/issues/126#issuecomment-468916234 the current `zrepl:placeholder` user property makes it hard to rename datasets because the placeholder status is determined by computing a hash of the dataset path and comparing it with the property value.
This PR
* changes `zrepl:placeholder` to a simple `on|off` property
* derives property status from the property source (`local`), avoiding the original problem of property inheritance in the original implementation
* provides a migration command that, based on the current zrepl configuration, migrates  property values to the new `on|off` schema
=> receiving side: placeholder as simple on|off property

.circleci/config.yml
* people need a CircleCI account to get the binary artifacts
* we want to give users who shall try out branch builds direct links to binary builds
=> build: CircleCI build artifact upload to self-hosted minio repo

Makefile, build.Dockerfile, build.installprotoc.bash, docs/changelog.rst
* protoc zip fetching
* Makefile:
* GOOS and GOARCH
* run vet on all targets
Note: freebsd/arm64 is apparently not supported
fixes #180
refs #181
=> build: Linux arm64 support

rpc/dataconn/timeoutconn/timeoutconn.go, rpc/dataconn/timeoutconn/timeoutconn_test.go
An actual end-to-end test on i386 would be nice before merging this.
On the other hand, this work merely makes zrepl compile on i386, we don't 'officially' support i386 because the Makefile doesn't produce a binary.
What do you think, @woodsb02?
=> fix #184 :  i386 build failure timeoutconn iovec len

client/status.go, daemon/logging/build_logging.go, docs/changelog.rst, endpoint/endpoint.go, platformtest/harness/harness.go, platformtest/harness/harness_test.go, platformtest/logmockzfs/logzfsenv, platformtest/logmockzfs/zfs, platformtest/platformtest.go, platformtest/platformtest_exec.go, platformtest/platformtest_logging.go, platformtest/platformtest_ops.go, platformtest/platformtest_parser_test.go, platformtest/tests/batchDestroy.go, platformtest/tests/getNonexistent.go, platformtest/tests/tests.go, platformtest/tests/undestroyableSnapshotParsing.go, transport/local/connect_local.go, util/envconst/envconst.go, zfs/versions.go, zfs/versions_destroy.go, zfs/versions_destroy_test.go, zfs/zfs.go
(This PR is based on top of the go modules PR, merge that one first)
=> batch snapshot destroys using comma syntax if supported

dist/systemd/zrepl.service
`systemd` can not parse the `ProtectHome` setting:
```
journalctl -u zrepl -p err
-- Logs begin at Sat 2019-08-24 03:04:22 CEST, end at Sun 2019-10-06 13:21:35 CEST. --
Okt 05 19:30:01 pidsley systemd[1]: /etc/systemd/system/zrepl.service:21: Failed to parse protect home value, ignoring: read-only   # DEBIAN STRETCH
sudo systemctl show zrepl|grep ^ProtectHome
ProtectHome=no
```
I just removed the trailing comment. I hope his meets your requirements:
Both `Stretch` and `Fedora 28` are outdated. 
Both settings work fine on my Arch Linux setup.
=> Fix invalid comment syntax

docs/installation.rst
A native `zrepl` package was recently added to [OmniOS](https://omnios.org) (an illumos distribution). It is currently built with Go 1.12, the Solaris arch and a few patches. In the future, it will move to Go 1.13 and the illumos arch.
Build recipe is here: https://github.com/omniosorg/omnios-extra/tree/master/build/zrepl
=> Add OmniOS (illumos distribution) to list of OSs

go.mod, go.sum
(go-netssh vendored util/circlog, so the circular dep is gone)
fixes build failure reported by @poettler-ric 
```
make ZREPL_VERSION=0.2.1 zrepl-bin
GO111MODULE=on go build -mod=readonly -ldflags "-X github.com/zrepl/zrepl/version.zreplVersion=0.2.1" -o "artifacts/zrepl-linux-amd64"
go: github.com/problame/go-netssh@v0.0.0-20191026123024-f34099f4f6b1 requires
github.com/zrepl/zrepl@v0.2.0 requires
github.com/golangci/lint-1@v0.0.0-20181222135242-d2cdd8c08219: invalid version: git fetch --unshallow -f origin in /builddir/go/pkg/mod/cache/vcs/ca789ff49d608cda239a48837cfeea6e9dcdb2bce20051383910eef46b623a33: exit status 128:
fatal: git fetch-pack: expected shallow list
```
=> build: go.mod: bump go-netssh and drop go-critic replaces

build/tools.go, config/config.go, daemon/prometheus.go, docs/changelog.rst, docs/configuration/monitoring.rst, docs/configuration/transports.rst, platformtest/harness/harness.go, platformtest/platformtest_zpool.go, platformtest/tests/undestroyableSnapshotParsing.go, transport/tcp/serve_tcp.go, transport/tls/serve_tls.go, util/tcpsock/tcpsock.go, util/tcpsock/tcpsock_freebind_freebsd.go, util/tcpsock/tcpsock_freebind_linux.go, util/tcpsock/tcpsock_freebind_unsupported.go, zfs/zfs.go
Allows to bind to an address even if it is not actually (yet or ever)
configured. Fixes #238
Rationale:
https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/#whatdoesthismeanformeadeveloper
=> net: Enable IP_FREEBIND on listeners

daemon/job/build_jobs.go, daemon/job/build_jobs_test.go
Before this was false positiv interpreted as overlapping filesystem.
```
zpool/foo
zpool/foobar
```
This PR fixes this and marks it as non-overlapping.
=> daemon/job/build_jobs: fix validateReceivingSidesDoNotOverlap

client/migrate.go, client/testcmd.go, daemon/snapper/snapper.go, endpoint/endpoint.go, endpoint/endpoint_zfs.go, endpoint/endpoint_zfs_helpers.go, platformtest/platformtest_zpool.go, platformtest/tests/batchRelease.go, platformtest/tests/getNonexistent.go, platformtest/tests/helpers.go, platformtest/tests/idempotentBookmark.go, platformtest/tests/idempotentDestroy.go, platformtest/tests/idempotentHold.go, platformtest/tests/replicationCursor.go, platformtest/tests/resumeTokenParsing.go, platformtest/tests/sendArgsValidation.go, platformtest/tests/undestroyableSnapshotParsing.go, zfs/encryption.go, zfs/placeholder.go, zfs/resume_token.go, zfs/versions_destroy.go, zfs/versions_destroy_test.go, zfs/zfs.go, zfs/zfs_test.go
Laying the groundwork to logging all /bin/zfs calls.
=> zfs: use exec.CommandContext everywhere

zfs/zfscmd/zfscmd_logging.go, zfs/zfscmd/zfscmd_platform_test.go
=> zfscmd: fix nil deref in waitPostLogging when command was killed

endpoint/endpoint_zfs_abstraction.go
```
cs@cstp:[~/zrepl/zrepl]: artifacts/zrepl-linux-amd64 zfs-abstraction release-stale --dry-run
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9de971]
goroutine 1 [running]:
github.com/zrepl/zrepl/endpoint.listStaleFiltering(0xc00012b700, 0x5, 0x8, 0x0, 0x13ccb58)
/endpoint/endpoint_zfs_abstraction.go:736 +0x281
github.com/zrepl/zrepl/endpoint.ListStale(0xe3ae20, 0xc00026b740, 0x0, 0xe27c60, 0x13ccb58, 0xc0001d8690, 0x0, 0x0, 0x0, 0x1, ...)
/endpoint/endpoint_zfs_abstraction.go:698 +0x3fd
github.com/zrepl/zrepl/client.doZabsReleaseStale(0xe3ae20, 0xc00026b740, 0x13a28a0, 0xc000151be0, 0x0, 0x1, 0x5705b4, 0xc0002686e0)
/client/zfsabstractions_release.go:83 +0x1a0 …
```
=> fixup e0b5bd7: crash on endpoint.ListStale if replication-cursor-v1 bookmark present

docs/installation.rst, docs/installation/apt-repos.rst, docs/installation/compile-from-source.rst, docs/installation/freebsd-jail-with-iocage.rst, docs/installation/packages.rst, docs/installation/user-privileges.rst, docs/installation/what-next.rst, docs/tutorial.rst
Add a tutorial page https://github.com/zrepl/zrepl/issues/219 instructing how to set up a FreeBSD jail using `iocage`.
I have left instructions for both using a iocage plugin and for a manual install. Let me know if you think it makes more sense to remove the plugin instructions
For the plugin, it has been added to the [ix-plugin-hub](https://github.com/ix-plugin-hub/iocage-plugin-index/blob/master/zrepl.json), note the plug-in has not yet been merged into a release branch https://github.com/ix-plugin-hub/iocage-plugin-index/pull/71#issuecomment-617449084, at which point it will be available via the FreeNAS UI and cli. Until then I have left instructions on how to use the plugin by downloading the json file directly. Once it has been added, following command can be used instead of …
=> Add FreeBSD jail tutorial

daemon/job/active.go, dist/grafana/grafana-prometheus-zrepl.json, docs/changelog.rst, replication/report/replication_report.go
Implements the proposed prometheus gauge in https://github.com/zrepl/zrepl/issues/338
I'm not entirely sure what to return in `GetFailedFilesystemsCount` in these cases:
- Replication is not done yet -> AFAICS it does not matter, since the prometheus gauge is only set after replication exits, so I opted for `0`
- Replication fails and filesystem reports are still empty -> I opted for `-1` and an explaination in the metric description
Let me know what you think.
I have tested this locally::
- target not reachable -> `-1` as expected
- receiver interrupted while sending -> correct count
- successful replication -> 0
- multiple jobs -> works correctly
=> Implement prometheus gauge for failed filesystem replications

docs/configuration/snapshotting.rst
The link to the sample hook file currently goes to sampleshooks/template.sh instead of samples/hooks/template.sh
=> Fixing link to template.sh sample hook file

client/status/viewmodel/bytesprogresshistory.go, config/config.go, config/samples/bandwidth_limit.yml, daemon/job/build_jobs.go, daemon/job/build_jobs_sendrecvoptions.go, daemon/job/build_jobs_test.go, docs/configuration/sendrecvoptions.rst, docs/supporters.rst, endpoint/endpoint.go, go.mod, go.sum, util/bandwidthlimit/bandwidthlimit.go, util/datasizeunit/datasizeunit.go, util/datasizeunit/datasizeunit_test.go
This PR adds the ability to configure a job-level bandwidth / data rate limit, based on a token bucket.
The limit is applied _above_ the `transport`, and only to the `zfs send` / `zfs recv` operation.
This fixes #339.
Also, the data rate display in `zrepl status` can average towards the wrong value (#497). 
This PR includes a workaround that disables the averaging.
Todo
- Determine trade-offs with  around with different values for `bucket_capacity`
- Watch out for CPU overhead
- Check 1: if no bandwidth limit is configured, the overhead should be practically zero.
- Check 2: Determine CPU overhead in Multi-GiB/s workloads
- Hardware information (`cat /proc/cpuinfo` or similar)
- zrepl job's `transport.type`
- Average CPU utilization in `%` before and after enabling a bandwidth limit
- If …
=> job-level bandwidth limit

client/status/viewmodel/render.go
This is a fixup of
commit https://github.com/zrepl/zrepl/commit/b00b61e9677209790ec9a018036e24b8ae336d52
Author: Christian Schwarz <me@cschwarz.com>
Date:   Sun Nov 21 15:15:23 2021 +0100
status: user-visible replication step number should start at 1
fixes https://github.com/zrepl/zrepl/issues/589
refs https://github.com/zrepl/zrepl/issues/538
---
@gdevenyi please test this fix.
=> status: fix over-counted step when status != stepping

docs/changelog.rst, replication/logic/diff/diff.go, replication/logic/diff/diff_test.go
Fixes #490
This is an old bug that I found and have been using this fix since. I've updated it to the newest version and seems to be working fine. @kpfleming please test it if you have the resources for it.
@problame please review.
=> Filter bookmarks when searching filesystem versions.

config/config.go, docs/configuration/misc.rst
For this kind of debugging, we switched to env vars a while ago.
For example, ZREPL_RPC_DEBUG.
I don't think we have a substitute for the RPCLog stuff.
However, NetConnLogger is still in the codebase.
obsoletes https://github.com/zrepl/zrepl/pull/661
=> remove unused JobDebugSettings along with docs

.circleci/config.yml
CircleCI artifacts are available publicly.
And regarding expiration of artifacts, it doesn't really matter because I delete minio artifacts after 30d as well.
=> build: circleci: stop using minio for artifact storage

docs/configuration/conflict_resolution.rst, docs/configuration/jobs.rst, docs/configuration/replication.rst, docs/global.rst.inc
Added them to push- and pull-jobs in jobs.rst, seems to have been forgotten? :)
=> docs/jobs: add replication- conflict_resolution-options to active jobs

docs/pr.rst
I found the problem regarding ``keep_bookmarks`` confusing and scary but couldn't find further information about this option in the documentation because the option was removed since the talks were given.
This small change adds a note that the keep_bookmarks option was removed in 0.4.0.
=> keep_bookmarks option was removed

client/status/viewmodel/render.go, daemon/pruner/pruner.go, replication/report/replication_report.go
Hide the progress bar once all filesystems reach terminal state on pruner.
Before:
After:
=> Fix issue #165. zrepl status: hide progress bar once all filesystems reach terminal state

.circleci/config.yml, daemon/job/build_jobs.go, daemon/job/build_jobs_test.go, docs/configuration/overview.rst
Because some jobs add client identity to root_fs and other jobs don't do that,
we can't reliable detect overlapping of filesystems. And and the same time we
need an ability to use equal or overlapped root_fs for different jobs. For
instance see this config:
```
- name: "zdisk"
type: "sink"
root_fs: "zdisk/zrepl"
serve:
type: "local"
listener_name: "zdisk"
```
and
```
- name: "remote-to-zdisk"
type: "pull"
connect:
type: "tls"
root_fs: "zdisk/zrepl/remote"
```
As you can see, two jobs have overlapped root_fs, but actually datasets are not
overlapped, because job `zdisk` save everything under `zdisk/zrepl/localhost`,
because it adds client identity. So they actually use two different filesystems:
`zdisk/zrepl/localhost` and `zdisk/zrepl/remote`. And we can't detect this
situation during …
=> Allow same root_fs for different jobs: sinks and so on

config/config.go, config/config_minimal_test.go, config/config_test.go, packaging/systemd-default-zrepl.yml
fixes https://github.com/zrepl/zrepl/issues/784
obsoletes https://github.com/zrepl/zrepl/pull/787
=> treat empty `jobs` & empty YAML as valid & ship empty `jobs` in deb/rpm

README.md
Bountysource is dead.
https://www.theblockchain-group.com/wp-content/uploads/2023/11/TBG-CP17112023.pdf
=> Remove dead Bountysource link

dist/systemd/zrepl.service
It pains me to do it, but, especially with hooks, the Protect
settings are too restrictive.
I wish there were a systemd API that allowed us to self-sandbox,
using these settings, _after_ parsing the config.
fixes https://github.com/zrepl/zrepl/issues/735
=> dist/systemd: remove various Protect* settings

packaging/deb/Dockerfile, packaging/deb/debian/control, packaging/deb/debian/rules, packaging/deb/debian/zrepl.bash-completion
fixes https://github.com/zrepl/zrepl/issues/794
=> deb: place bash completion at correct path, using debhelper

go.mod, go.sum, internal/client/status/status_interactive.go, internal/client/status/status_legacy.go
While investigating https://github.com/zrepl/zrepl/issues/700
I checked in on `zrepl status` dependencies and found that
`cview`, which was/is a fork of tview, appears to be unmaintained.
We switched to it 4.5 years ago in a58ce74.
Checking now, `github.com/rivo/tview` seems to be somewhat maintained
again.
I also checked what k9s uses because that tool came to mind as a Go
terminal UI app.
It does use `tview`, but, a fork that has diverged substantially.
Maybe in another 4.5 years stuff the ecosystem has consolidated...
refs https://github.com/zrepl/zrepl/issues/700
=> zrepl status: switch back to tview from cview & upgrade to latest

packaging/rpm/Dockerfile
The `make rpm-build` started failing with
```
find-debuginfo: starting
Extracting debug info from 1 files
*** ERROR: No build ID note found in /build/src/artifacts/rpmbuild/BUILD/zrepl-v0.6.1.47.gbae2bd2-build/BUILDROOT/usr/bin/zrepl
error: Bad exit status from /var/tmp/rpm-tmp.bYHLzG (%install)
```
This must be a change in Fedora (prob new Fedora major release).
Seize the opportunity to
1. stop building from `:latest`, and
2. build with an LTS RPM distro to improve zrepl RPM compatibility (no problems so far AFAIK but this seems sensible)
=> build: rpm: build with almalinux:8 image instead of fedora:latest, fixing `make rpm-build`
