zrepl/zrepl

Gopkg.lock, Makefile, cmd/autosnap.go, cmd/bashcomp.go, cmd/config.go, cmd/config_job_control.go, cmd/config_job_local.go, cmd/config_job_pull.go, cmd/config_job_source.go, cmd/config_logging.go, cmd/control.go, cmd/daemon.go, cmd/logging_formatters.go, cmd/prune.go, cmd/replication.go, cmd/test.go, docs/configuration.rst, docs/configuration/logging.rst, docs/configuration/misc.rst, docs/configuration/preface.rst, docs/index.rst, docs/installation.rst, docs/tutorial.rst, docs/usage.rst, logger/datastructures.go, logger/logger.go, util/io.go
=> zrepl control status subcommand

config/config.go, config/config_global_test.go, daemon/logging/build_logging.go, daemon/logging/logging_outlets.go, docs/configuration/logging.rst
Here's my contribution to issue #60, adding configurable syslog facility to zrepl.
=> Ximalas syslog facility

daemon/logging/build_logging.go, zfs/replication_history.go, zfs/zfs.go, zfs/zfs_test.go
addresses problems reported in #131 
@JMoVS  please report back whether these changes fixed your problems
=> fix handling of spaces in dataset names

daemon/snapper/snapper.go, daemon/snapper/state_string.go
=> snapper: retry on errors during syncUp and log them

Gopkg.lock, endpoint/endpoint.go, replication/logic/replication_logic.go, rpc/rpc_client.go, util/semaphore/semaphore.go, util/semaphore/semaphore_test.go
=> hotfix #161 for 0.1: limit concurrency of zfs send & recv commands

transport/local/serve_local.go
fixes #173
(amendment of 0e419c11df2bc45feb6edb7d82a309b0fe174875)
=> transport/local: fix "client-provided callback did block on send" crash

.circleci/config.yml
disables artifact upload to external minio repo
=> build/circleci: handle forked PR builds

docs/installation.rst
Unable to quickly test if layouting works, I hope it does!
=> Include homebrew installation

rpc/dataconn/dataconn_client.go, rpc/dataconn/frameconn/frameconn.go
=> rpc/dataconn: ECONNRESET + other log noise

docs/installation.rst
As discussed on
https://github.com/zrepl/zrepl/pull/226#issuecomment-538737870
=> docs: include Arch Linux installation

docs/installation.rst
@janisstreib could you have a look & comment?
=> docs: install: apt: make apt repo add snippet idempotent & bash-compatible

daemon/snapper/snapper.go, docs/changelog.rst, docs/configuration/snapshotting.rst, docs/tutorial.rst
=>  daemon/snapper: refactor sync-up algorithm + warn about FSes awaiting first sync point

client/status.go
```
Job: pull_monitor
Type: pull
Replication:
Attempt #1
Status: fan-out-filesystems
Progress: [=======|-------------------------------------------] 46.0 MiB / 295.8 MiB @ 5.3 MiB/s 10d  5h  0m  23s remaining
rpool                 STEPPING (step 1/12, 624 B/7.3 KiB) next: @zrepl_20200122_170738_000 => @zrepl_20200122_170811_000 (encrypted=sender-dependent)
rpool/data            STEPPING (step 1/12, 624 B/7.3 KiB) next: @zrepl_20200122_170740_000 => @zrepl_20200122_170812_000 (encrypted=sender-dependent)
rpool/data/postgresql STEPPING (step 1/11, 46.0 MiB/295.8 MiB) next: @zrepl_20200122_170741_000 => @zrepl_20200122_170807_000 (encrypted=sender-dependent)
Pruning Sender:
...
Pruning Receiver:
...
```
This will
fix #98
=> WIP: client/status: add duration estimation

go.mod, go.sum
by updating golang:sys dependency
=> Fix build on FreeBSD on aarch64

Makefile
=> build: add linux/armv7 target

endpoint/jobid.go
Signed-off-by: InsanePrawn <insane.prawny@gmail.com>
=> Fix typos in jobid.go

.circleci/config.yml, tlsconf/tlsconf.go
=> build: go1.14 + address tlsconf deprecation notice

Makefile, cli/cli.go, docs/changelog.rst
=> zsh completions

lazy.sh
- Emit warning and return 1 when no cmd is specified
- Explicitly warn when gopath is not in PATH
- get docdep requirements from lazy.sh parent dir, not $GOPATH/src/zrepl/zrepl
- Fix `release` cmd
- replace `! -z` with `-n`
Signed-off-by: InsanePrawn <insane.prawny@gmail.com>
=> lazy.sh: various fixes

config/config.go, daemon/job/active.go, daemon/job/build_jobs_test.go, docs/configuration/replication.rst, endpoint/endpoint.go, go.mod, go.sum, platformtest/tests/replication.go, replication/driver/replication_driver.go, replication/driver/replication_driver_test.go, replication/logic/replication_logic.go, replication/logic/replication_logic_policy.go, replication/replication.go
=> replication: simplify parallel replication variables & expose them in config

docs/configuration/sendrecvoptions.rst
Signed-off-by: InsanePrawn <insane.prawny@gmail.com>
=> Docs: Add note about `zfs recv -x mountpoint` with zvols

dist/openrc/zrepl
This PR includes a simple service file for openrc-based distributions such as Gentoo or Alpine Linux.
=> Include openrc service file

daemon/filters/fsmapfilter.go, dist/grafana/grafana-prometheus-zrepl.json, endpoint/endpoint.go, zfs/mapping.go, zfs/prometheus.go, zfs/zfscmd/zfscmd_context.go
The idea is to report missing datasets through Prometheus. I used different metrics for different job types as it is easier to measure and debug in development, so it's an open question if it would be better to use one metric for all job types.
As this is my first open source project written in Go, please do tell me how to improve this code if you have any suggestions.
=> Report if dataset does not exist but is in configuration

.circleci/config.yml
fixes https://github.com/zrepl/zrepl/issues/762
=> build: ci: fix `quickcheck-docs` for external PRs

docs/installation/compile-from-source.rst
=> add missing newline for codeblock in docs/compile-from-source.rst

.golangci.yml, internal/zfs/versions.go
No issues found, tested that the lint works by changing code locally.
fixes https://github.com/zrepl/zrepl/issues/5
=> lint: add lint checking for time.Equal

README.md
fixes https://github.com/zrepl/zrepl/issues/374
=> README: document patch release procedure
